version: 2.1
jobs:
  build:
    docker:
      - image: node:dubnium-alpine
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: npm install
          command: |
            npm ci
      - run:
          name: run ci test
          command: |
            npm run ci
